services:
  react-app:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: react-app
    working_dir: /app
    volumes:
      - ./fe:/app # Mount the React app directory
      - /app/node_modules # Prevent overriding node_modules
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
    command: >
      sh -c "npm install && npm start"